### ISSUE TITLE
Uncaught (in promise): TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by maxrodro** [vcooley/nativescript-input-mask#10]
Hi, update to the latest version of Nativescript and now the InputMask gives the following error:
I really appreciate the help you can give me

Error:
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'extend' of undefined
JS: TypeError: Cannot read property 'extend' of undefined
JS:     at __extends (/data/data/org.nativescript.demo/files/internal/ts_helpers.js:51:36)
JS:     at file: **node_modules\nativescript-input-mask\angular\input-mask.directive.js:12:0**
JS:     at Object...**/node_modules/nativescript-input-mask/angular/input-mask.directive.js** (file: node_**modules\nativescript-input-mask\angular\input-mask.directive.js:35:1**)
JS:     at __webpack_require__ (file: src\webpack\bootstrap:74:0)
JS:     at Object.../node_modules/nativescript-input-mask/angular/input-mask.module.js (file: node_modules\nativescript-input-mask\angular\input-mask.module.js:5:29)
JS:     at __webpack_require__ (file: src\webpack\bootstrap:74:0)
JS:     at Object.../node_modules/nativescript-input-mask/angular/index.js (file: node_modules\nativescript-input-mask\angular\index.js:6:9)
JS:     at __webpack_requ...

package.json
{
  "nativescript": {
    "id": "org.nativescript.demo",
    "tns-ios": {
      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/core": "6.6.0-next-2020-05-08-112112-01",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "nativescript-angular": "^8.21.0",
    "nativescript-cfalert-dialog": "^1.0.15",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-input-mask": "^1.0.5",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-observable": "^2.0.2",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "nativescript-windowed-modal": "^6.2.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.5.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "^1.5.1",
    "node-sass": "^4.13.1",
    "typescript": "~3.5.3"
  },
  "gitHead": "42f2a6a9c94eaf9c68d2a41e0daaa1a2544bc28f",
  "readme": "NativeScript Application"
}

tsconfig.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ],
            "*": [
                "./node_modules/*",
                "./node_modules/tns-core-modules/*",
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}

tsconfig.tns.json
{
    "extends": "./tsconfig",
    "compilerOptions": {
        "module": "esNext",
        "moduleResolution": "node"
    }
}

**Comment by comporell** [comment]
any updates on this?

**Comment by itsmerockingagain** [comment]
I am also facing same issue, please help in this
